"""Runs both fixture sets through SqlValidator and emits the README number.

The report is generated by the test run, never typed by hand. That is the whole
difference between the count being a fact and being decoration.
"""

from __future__ import annotations

import collections
from pathlib import Path

import pytest

from guardrails.tests.conftest import MAX_ROWS, load_cases
from guardrails.validator import SqlValidator

UNSAFE = load_cases("unsafe.yaml")
SAFE = load_cases("safe.yaml")

REPORT_PATH = Path(__file__).resolve().parent.parent / "REPORT.md"


@pytest.mark.parametrize("case", UNSAFE, ids=[c["id"] for c in UNSAFE])
def test_unsafe_is_rejected(case: dict, validator: SqlValidator) -> None:
    """Every unsafe fixture must come back ok=False, and nothing may raise."""
    result = validator.validate(case["sql"])
    assert result.ok is False, (
        f"{case['id']} was ACCEPTED but must be rejected.\n"
        f"  category: {case['category']}\n"
        f"  why:      {case['why']}\n"
        f"  rewrote:  {result.rewritten_sql}"
    )
    assert result.reason, f"{case['id']} rejected without a reason for the repair node"


@pytest.mark.parametrize("case", SAFE, ids=[c["id"] for c in SAFE])
def test_safe_is_accepted(case: dict, validator: SqlValidator) -> None:
    """Every safe fixture must come back ok=True with the expected rewrite.

    Without this half of the suite, a validator that rejects everything would
    score 100% on unsafe.yaml.
    """
    result = validator.validate(case["sql"])
    assert result.ok is True, f"{case['id']} was REJECTED: {result.reason}"
    assert result.rewritten_sql, f"{case['id']} accepted without rewritten SQL"
    assert result.limit_injected is case["expect_limit_injected"], (
        f"{case['id']}: expected limit_injected="
        f"{case['expect_limit_injected']}, got {result.limit_injected}"
    )


def test_row_cap_is_actually_applied(validator: SqlValidator) -> None:
    """The cap is enforced, not merely detected."""
    result = validator.validate("SELECT id FROM orders LIMIT 10000000")
    assert result.ok
    assert f"LIMIT {MAX_ROWS}" in result.rewritten_sql


def test_write_report(validator: SqlValidator) -> None:
    """Emit guardrails/REPORT.md. The README quotes these numbers."""
    by_category: dict[str, collections.Counter] = collections.defaultdict(
        collections.Counter
    )
    unsafe_rejected = 0
    for case in UNSAFE:
        rejected = not validator.validate(case["sql"]).ok
        unsafe_rejected += rejected
        by_category[case["category"]]["total"] += 1
        by_category[case["category"]]["rejected"] += rejected

    safe_accepted = sum(1 for case in SAFE if validator.validate(case["sql"]).ok)

    lines = [
        "# Guardrail adversarial test report",
        "",
        "Generated by `pytest guardrails/tests/test_adversarial.py`. Do not edit by hand.",
        "",
        f"- **Unsafe statements rejected: {unsafe_rejected} / {len(UNSAFE)}**",
        f"- **Legitimate queries accepted: {safe_accepted} / {len(SAFE)}**",
        f"- Row cap: {MAX_ROWS}",
        "",
        "| Category | Rejected | Total |",
        "| --- | --- | --- |",
    ]
    for category in sorted(by_category):
        counts = by_category[category]
        lines.append(f"| {category} | {counts['rejected']} | {counts['total']} |")

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    assert unsafe_rejected == len(UNSAFE)
    assert safe_accepted == len(SAFE)
