/**
 * Shows the model output and the executed statement side by side. They differ
 * whenever the guardrail rewrote something -- usually an injected LIMIT -- and
 * showing only one of them would hide that the guardrail did any work.
 */
export default function SqlPanel({ response }) {
  const { sql, executed_sql: executedSql, explanation } = response;
  const rewritten = sql && executedSql && sql.trim() !== executedSql.trim();

  return (
    <section className="panel">
      <h2>SQL</h2>
      {explanation && <p className="sub">{explanation}</p>}

      <h3>Generated by the model</h3>
      <pre className="sql">{sql || "(none)"}</pre>

      <h3>
        Executed after guardrail{" "}
        {rewritten && <span className="tag warn">rewritten</span>}
      </h3>
      <pre className="sql">{executedSql || "(nothing was executed)"}</pre>
    </section>
  );
}
